### ISSUE TITLE
Automatic localization change

### ISSUE THREAD

**Issue by w1th0utme** [TownyAdvanced/TownyMenus#25]
I have own-lang.yml in towny and also have the contents of this file duplicated in override > global.yml. In towny menus I also use the own-lang.yml language file in the override folder. But sometimes the plugin randomly loads the standard localization en-US.yml and I don't know why.

**Comment by CerealAxis** [comment]
Yes, I am in the same situation. After modifying the lang file in TownyMenus, once restarted, everything will be restored to its original state, so there is no way to change the implementation of localized languages
![image](https://github.com/TownyAdvanced/TownyMenus/assets/119841629/23aa0141-4556-4289-ab24-9835779053e3)

**Comment by Warriorrrr** [comment]
In what folder is the file you're editing? You shouldn't touch any of the files in the reference folder, as those will be overridden. Instead use the override folder (https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#multi-language).

**Comment by CerealAxis** [comment]
> 您正在编辑的文件在哪个文件夹中？您不应触摸引用文件夹中的任何文件，因为这些文件将被覆盖。请改用覆盖文件夹 （https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#multi-language）。

sorry,my problem.

**Comment by w1th0utme** [comment]
I have the file in the override folder

**Comment by NeotenySS** [comment]
Confirming the problem.
I use a separate file and also use the global.yml file to create a translation by multi-language, but it doesn't help, the plugin ignores the conditions and draws the translation from the en_US.yml file
Trying to change the content in en_US.yml restores it and the global.yml file is ignored.
@Warriorrrr

**Comment by Warriorrrr** [comment]
Changing lang strings in the override folder works for me, I can not reproduce the issue. The global.yml file probably only exists in towny currently.
