### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by w1th0utme** [TownyAdvanced/TownyMenus#26]
![image](https://github.com/TownyAdvanced/TownyMenus/assets/137961937/0c8ba4c8-31ca-48b0-b1e2-c716bb371e91)

**Comment by Warriorrrr** [comment]
This should already be fixed in the latest commit, can you try reproducing on the snapshot version? https://github.com/TownyAdvanced/TownyMenus/suites/13999874411/artifacts/781149972
