### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by yngdrms** [TownyAdvanced/TownyMenus#42]
ver: 1.20.1
TownyMenus version 0.0.7
Towny version 0.100.1.11

https://pastes.dev/pkv6oDZtxk
https://pastes.dev/z8mosTG2FT
https://pastes.dev/pRQOciiZ4M

**Comment by Warriorrrr** [comment]
Will be partially fixed by https://github.com/TownyAdvanced/TownyMenus/pull/41

**Comment by Warriorrrr** [comment]
Fixed by e2e2120ca40503924275b3cb4955f55638fa5786
