### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Shidapu** [TownyAdvanced/TownyMenus#5]
/tm doesn't work with FasAsyncWorldEdit
/townmenu does work nicely.

**Comment by Warriorrrr** [comment]
/tm was not an existing alias for /townymenu, it has been added in d9e77f4cbadd6f22a03e56adc5e93c7f31eb7a0e. If it still doesn't work after that commit, I recommend you use bukkit's [commands.yml](https://bukkit.fandom.com/wiki/Commands.yml) to force it to use TownyMenu's command
